# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: api_rw
      POSTGRES_DB: godockapp

  adminer:
    image: go-dock-app
    restart: always
    ports:
      - 3344:3344
    depends_on:
      - db
